# Generated by Django 3.1.2 on 2021-04-14 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_Code_text',
            new_name='lesson_code_text',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_psudo_Code',
            new_name='lesson_psudo_code',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='votes',
            new_name='module_number',
        ),
    ]
