# Generated by Django 3.1.2 on 2021-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_auto_20210414_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_text',
            field=models.TextField(default='no lesson text'),
        ),
    ]
