# Generated by Django 2.2.5 on 2021-04-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_lesson_lesson_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_text',
        ),
    ]
