# Generated by Django 2.2.5 on 2021-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_remove_lesson_lesson_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_text',
            field=models.TextField(default='no lesson text'),
        ),
    ]
