# Generated by Django 2.2.5 on 2021-05-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0005_lesson_lesson_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_title',
            field=models.CharField(default='no lesson title', max_length=200),
        ),
    ]
