# Generated by Django 2.2.5 on 2021-05-03 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0006_lesson_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_title',
        ),
    ]
