# Generated by Django 2.2.5 on 2021-05-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0007_remove_lesson_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_text',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_title',
            field=models.CharField(default='no lesson title', max_length=200),
        ),
    ]
