# Generated by Django 2.2.5 on 2021-05-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0008_auto_20210502_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
