# Generated by Django 2.2.5 on 2021-05-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0010_auto_20210502_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
